## Error Handling
4.B.1 Handling errors / Working with try / except

In [3]:

# without try / except
first_num = float(input('% to calculate as decimal (provide a whole number): '))

pct_as_dec = first_num / 100

print(pct_as_dec)

% to calculate as decimal (provide a whole number):  bad value


ValueError: could not convert string to float: 'bad value'

In [5]:
# with try / except

try:
    first_num = float(input('% to calculate as decimal (provide a whole number): '))
    pct_as_dec = first_num / 100
except:
    print('Invalid input. Please try again')
else:
    print(pct_as_dec)
finally:
    print('Run again to calculate another decimal value, ')

% to calculate as decimal (provide a whole number):  bumblebee


Invalid input. Please try again
Run again to calculate another decimal value, 


In [14]:
try:
    fnum = float(input('Number to divide: '))
    snum = float(input('Second number to use as divisor: '))
    div_result = fnum / snum
except ValueError:
    print('Invalid input: must be a number. Please try again')
except ZeroDivisionError:
    print('Cannot divide by zero.')
except:
    print('Encountered an error.' )
else:
    print(div_result)
finally:
    print('Run again to calculate another decimal value. ')

Number to divide:  47
Second number to use as divisor:  0


Cannot divide by zero.
Run again to calculate another decimal value. 


In [16]:
# another alternative 
try:
    fnum = float(input('Number to divide: '))
    snum = float(input('Second number to use as divisor: '))
    div_result = fnum / snum
except (ValueError, ZeroDivisionError): # this is also a valid soluction to the same problem
    print('Error: must be a number other than zero')
except:
    print('Encountered an error.' )
else:
    print(div_result)
finally:
    print('Run again to calculate another decimal value. ')

Number to divide:  47
Second number to use as divisor:  bumblebee


Error: must be a number other than zero
Run again to calculate another decimal value. 


### can nest try/ except blocks PG 74

In [25]:
try:
    f = open("sample.txt.txt") # make sure name matches with the file name you have it save as 
    try:
        sample_content = f.read()
    except:
        print(f'Cannot read from file')
    else:
        print(sample_content)
    finally:
        f.close()
except:
    print("Error, cannot retrieve file")

Ice Cream Shop Daily Sales Report
Date: July 14, 2025
Location: Sunnyside Scoops

Flavor,Scoops Sold,Price Per Scoop,Total Revenue
Vanilla,42,$2.50,$105.00
Chocolate,38,$2.50,$95.00
Strawberry,27,$2.50,$67.50
Mint Chip,31,$2.75,$85.25
Rocky Road,19,$2.75,$52.25
Butter Pecan,14,$2.75,$38.50
Mango Sorbet,22,$3.00,$66.00
Cookie Dough,35,$3.00,$105.00

Total Scoops Sold: 228
Total Revenue: $614.50
Best Seller: Vanilla
Slowest Seller: Butter PecanWeather was sunny and mild


In [27]:
try:
    f = open("sample.txt.txt") #still opening in "r" mode
    try:
        sample_content = f.write("\n") # trying to write to the file 
        sample_content = f.write("Customer survey was sent out via email mailing list.")
    except:
        print(f'Cannot read from file')
    else:
        print(sample_content)
    finally:
        f.close()
except:
    print("Error, cannot retrieve file")

Cannot read from file


### using try / except with a lop PG 75

In [37]:
print('Division calculator:')
first_n = None

while first_n == None:
    try:
        first_n = float(input('First number to divide: '))
    except:
        print('Invalid input! Must be a number')

second_n = None
answer = None

while second_n == None:
    try:
        second_n = float(input('Second number to divide by: '))
        answer = first_n / second_n
    except ValueError:
        print('Must be a number')
    except ZeroDivisionError:
        print('Number cannot be zero')
        second_n = None  # so it can go back and ask for second number again 

print(answer)
        

Division calculator:


First number to divide:  cactus


Invalid input! Must be a number


First number to divide:  988
Second number to divide by:  0


Number cannot be zero


Second number to divide by:  9


109.77777777777777


In [38]:
print('Division calculator:')
first_n = None

while first_n == None:
    try:
        first_n = float(input('First number to divide: '))
    except:
        print('Invalid input! Must be a number')

second_n = None
answer = None

while second_n == None:
    try:
        second_n = float(input('Second number to divide by: ')) #this woudl not result in an error if the number is zero  
        answer = first_n / second_n
    except: 
        pass # would terminate the lop so you get end of program, but it's less informative
print(answer)
        

Division calculator:


First number to divide:  100
Second number to divide by:  0


None


In [42]:
#another example of try / except combined with a loop that's operatingon file contents

try:
    with open("sample.txt.txt") as f:  # if no sample2.txt then will trigger except block
        contents = f.readlines() 
except FileNotFoundError:
    print('Error:file not found')
else:
    with open("sales_data.csv", "a") as output:
        for i in contents:
            if "," in i:
                output.write(i)
    print('Output complete.')
finally:
    print('Run program again to process another file.')

Output complete.
Run program again to process another file.


# MODULE 5

### NumPy is a short for "Numerical Python"
NumPy arraysare optimized for faster processing 

### Creating arrays

In [44]:
import numpy as np

a = np.array([11,12,13,14,15])
    

In [45]:
print(a)

[11 12 13 14 15]


In [46]:
print(type(a))


<class 'numpy.ndarray'>


In [47]:
b = np.array(100) # zero-dimensional array

print(b)
print(type(b))

100
<class 'numpy.ndarray'>


In [49]:
c = np.array((('a', 'b', 'c'), ('d', 'e',6))) # tuples of tuples, starting with both string and int 

print(c)

[['a' 'b' 'c']
 ['d' 'e' '6']]


In [52]:
d = np.array(((1,2, None),(3,4,5)))

print(d)

[[1 2 None]
 [3 4 5]]


In [53]:
d2 = np.array(((1,2, np.nan),(3,4,5))) # numpy usues NaN

print(d2)  # result becomes float

[[ 1.  2. nan]
 [ 3.  4.  5.]]


In [55]:
bess_list = [
    ([(1,2,3)], [(4,5,6)]),
    ([(7,8,9)], [(10,11,12)]),
    ([(13,14,15)], [(16,17,18)])
]

e = np.array(bess_list)

print(e)

[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]


 [[[13 14 15]]

  [[16 17 18]]]]


In [56]:
print(e.ndim) # number of dimensions


4


In [57]:
print(e.size) # number of elements in the array

18


In [58]:
print(e.shape) # what is the size of each dimension, given as a tuple, lsited from the outside to the inside


# from starting list
# bess_list = [
#    ([(1,2,3)], [(4,5,6)]),
#    ([(7,8,9)], [(10,11,12)]),
#    ([(13,14,15)], [(16,17,18)])
# ]

# list includes 3 items (3 tuples) -- outermost dimension
# each tuple in the next layer contains 2 items(2 lists)
# each list in the nest layer 1 item ( a tuple)
# in the innermost tuple, there are 3 elemtns


(3, 2, 1, 3)


In [59]:
print(d2)
print(d2.ndim)
print(d2.size)
print(d2.shape)

[[ 1.  2. nan]
 [ 3.  4.  5.]]
2
6
(2, 3)


In [61]:
print(d2.T)
print(d2.T.shape) # transpose the dimension of the array

[[ 1.  3.]
 [ 2.  4.]
 [nan  5.]]
(3, 2)


In [62]:
## Usinf indexing with arrays 

In [63]:
print(d2[0][0]) # return the first value in the first dimension (zero position)

1.0


In [64]:
print(d2[1][1])

4.0


In [65]:
print(e)


[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]


 [[[13 14 15]]

  [[16 17 18]]]]


In [69]:
print(e[-1][-1][-1][-1]) # using the index through 4 dimensio

18


In [68]:
print(e[-1][-1][-1]) # using the index through 3 dimensions

[16 17 18]


In [72]:
print(e[1][1][0][1])  # pg 90 from work book

11
