# Exercise 5.A NumPy Fundamentals
This notebook practices creating and working with NumPy arrays, 
including one-dimesional, two-dimensional, and three-dimensional arrays.

In [5]:
# start by importing numpy as np
import numpy as np

## Array Basics

In [6]:
# Create a normal Python list
fruits = ['apple', 'banana', 'cherry', 'date']
# print the list
print(fruits)

['apple', 'banana', 'cherry', 'date']


In [7]:
# create a 1D NumPy array from fruits list
arr_1 = np.array(fruits)
# print the array
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [8]:
# Check the data type of values inside arr_1
print(arr_1.dtype)

# <U6  means:
# U = unicode string
# 6 = maximum string length is 6 characters

<U6


In [9]:
# create a 2D array
arr_2 = np.array([
    [10, 11, 12],
    [13, 14, 15]
])

# print the array
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [11]:
# print transposed version of arr_2
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [12]:
# Print original arr_2 again
print(arr_2)

# Using .T does NOT permanently change arr_2
# It only displays a transported version temporarily

[[10 11 12]
 [13 14 15]]


In [13]:
# Create another 2D array
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

# print the array
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [14]:
# Create arr_4 using specific values from arr_3
arr_4 = np.array([
    # Row 0, column 2 = 5
    arr_3[0, 2],
    # Row 1, column 1 = 4
    arr_3[1, 1]
])

#print arr_4
print(arr_4)

[5 4]


In [15]:
# create a 3D array of all 1's
# with 2 values in each dimension

arr_5 = np.ones((2, 2, 2))

#print the array 
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
