# Exercise 1.A NumPy: Manipulating Arrays

In [2]:
import numpy as np

## Looping Through Arrays

In [9]:
arrA = np.array([[11, 12, 13] , [14, 15, 16]]) # creating a variable as two-dimensional array 
print(arrA) # print result 

[[11 12 13]
 [14 15 16]]


In [17]:
# loop through the first dimension of arrA /// multiplied by 2
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [18]:
# loop through the second dimension of arrA /// multiplied by 2 
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


### Difference Between the First Loop and the Second Loop
In the first loop, the loop goes through the outer array only. Each iteration returns one whole row (or sub-list) at a time. 
This means the output shows lists, not individual values.
In the second loop, there is a nested loop. The first loop still goes through each row, but the second loop goes inside each row and 
accesses each individual element. This means the output shows the values one by one instead of lists.

In [28]:
#second dimension with variable loop_result
for x in arrA:
    for y in x:
        loop_result = x*2
print(loop_result)

# Explanation:
# This result is different because loop_result is updated many times inside the loops.
# Each new value replaces the previous one.
# Because print is outside the loops, only the last calculated value is shown.


[28 30 32]


## Joining and Stacking Arrays

In [29]:
# create variable
# axis = 0 so it will add more rows  NOT COLUMNS
joined_array_1 = np.concatenate((arrA, arrA), axis = 0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [30]:
# create variable with axis = 1 so columns will be add
joined_array_2 = np.concatenate((arrA, arrA), axis = 1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [31]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [32]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

# ValueError: all input arrays must have the same shape 

ValueError: all input arrays must have the same shape

In [33]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)
# concatenate joins arrays along axis=0 by default.
# This works because both arrays have the same number of columns.

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [34]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_2)

# ERROR explanation:
# axis=1 means adding columns.
# joined_array_1 has more rows than arrA.
# NumPy cannot match rows, so the operation fails.
# NumPy cannot join these arrays sideways because they do not have the same number of rows.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [37]:
k = np.hstack((arrA, arrA))
n = np.vstack((arrA, arrA))
m = np.dstack((arrA, arrA))

print(k)
print(n)
print(m)

# hstack(): stacks arrays horizontally (adds columns)
# vstack(): stacks arrays vertically (adds rows)
# dstack(): stacks arrays along a third dimension (depth)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [39]:
splitsky = np.split(joined_array_1, 2)
print(splitsky)

# Result:
# - This produces 2 arrays.
# - Each array is 2-dimensional.
# - Each array has the same shape (half the rows of joined_array_1).

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [41]:
spliterino = np.split(joined_array_1, 3)
print(spliterino)

# Result
# Error: array split does not result in an equal division
# This raises an error because joined_array_1 cannot be evenly divided into 3 equal parts.
# The number of rows is not divisible by 3.

ValueError: array split does not result in an equal division

## Searching and Replacing Array Values 

In [44]:
# create variable , to find each even number within arrA and if condition is met print arrA if not print 'odd'
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


In [45]:
print(arrA) # to give me an idea of how it changed 

[[11 12 13]
 [14 15 16]]


## Sorting and Filtering Arrays

In [46]:
# create a variable arrB as a 2D array
arrB = np.array([[7,6],
                [13,5],
                [7, 3]])
arrB_sorted = np.sort(arrB) # create another variable and assign it the sorted value of arrB
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [47]:
# Print the original array
print(arrB)

# Create a boolean mask for values less than 7
z = arrB < 7

# Filter arrB using the mask
arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [48]:
# Create a boolean mask for values >= 7
y = arrB >= 7

# Filter arrB using the new mask
arrD = arrB[y]

print(arrD)

[ 7 13  7]
