# Exercise 1.B NumPy Random 


In [3]:
import numpy as np 

## Generating Random Numbers

In [4]:
# create a r_1 variable that contains a random set of intergers btw 1 and 20 with a size of 2 elements 
r_1 = np.random.randint(1,21, size = 2)
print(r_1)

[18 20]


In [6]:
# Create a variable named r_2 that contains a random set of integers between 1 and
# 20 with a size of 1 row, 2 columns. Print r_2
r_2 = np.random.randint(1,21, size = (1,2))
print(r_2)

[[16  6]]


In [9]:
# Create a variable named r_3 that contains a random set of floats between 0 and 1
# with a size of 2 rows, 1 columns. Print r_3.
r_3 = np.random.random(size = (2,1))
print(r_3)

[[0.48197949]
 [0.9519025 ]]


In [10]:
# Create a variable named r_4 that contains a random set of integers between 20
# and 100 with a size of 4 rows, 5 columns. Print r_4.
r_4 = np.random.randint(20, 101, size = (4,5))
print(r_4)

[[45 80 47 67 94]
 [74 70 87 23 58]
 [79 88 45 65 89]
 [68 29 72 29 76]]


In [12]:
# Create a variable named r_5 that contains a random set of floats between 0 and 1
# with a size of 4 rows, 5 columns. Print r_5.
r_5 = np.random.random( size = (4, 5))
print(r_5)

[[0.67495519 0.360528   0.81453492 0.5638362  0.385182  ]
 [0.24615172 0.57551408 0.79198918 0.04241597 0.68515715]
 [0.30783527 0.79950597 0.25435754 0.86966257 0.79629167]
 [0.60105964 0.56755377 0.50585005 0.66959998 0.59171306]]


## Generating Random Choices from an Array

In [29]:
# Create a variable named students and assign it a 1-D array containing the names
# of 12 of your classmates. 8 WILL BE THE NUMBER OF STUDENTS IN MY CLASS so 4 are makeup
students = np.array(["Dahlia", "Brandon", "Edmund", "Destiney", "Luis", "Angel", "Kevin", "Jeremiah", "Hitrik", "Miranda", "Stefanie", "Bess"])
print(students)

['Dahlia' 'Brandon' 'Edmund' 'Destiney' 'Luis' 'Angel' 'Kevin' 'Jeremiah'
 'Hitrik' 'Miranda' 'Stefanie' 'Bess']


In [31]:
# Create a variable named call_on and use it to choose one random selection from
# students. Print call_on.
call_on = np.random.choice(students)
print(call_on)

Bess


In [32]:
# Create a variable named breakout_groups and use it to choose a random
# sampling from students that is 3 rows, 4 columns in size. Print
breakout_groups = np.random.choice(students, size = (3,4))  # ADDDING replce= False will eliminate duplicates
print(breakout_groups)

# This is NOT an effective way to assign breakout groups because
# the same student can appear multiple times and some students
# may not appear at all.

[['Edmund' 'Stefanie' 'Brandon' 'Brandon']
 ['Hitrik' 'Stefanie' 'Dahlia' 'Edmund']
 ['Destiney' 'Angel' 'Hitrik' 'Destiney']]


In [37]:
# Weighted random selections (5 picks)
p_values = [
    0.30,  # Dahlia (30% chance)
    0.10,  # Brandon
    0.10,  # Edmund
    0.05,  # Destiney
    0.05,  # luis
    0.10,  # Angel
    0.10,  # Kevin
    0.05,  # Jeremiah
    0.05,  # Hritrik
    0.05,  # Miranda
    0.05,  # Stefanie
    0.00   # Bess (0% chance)
]

call_on_weighted = np.random.choice(
    students,
    size=5,
    p=p_values
)

print(call_on_weighted)

# Dahlia has a 30% chance of being selected.
# Bess has a 0% chance and will never be selected.
# Other students have smaller probabilities.

['Edmund' 'Kevin' 'Edmund' 'Edmund' 'Dahlia']


## Generating a Normal Distribution 

In [38]:
# Create a variable named bell_curve and assign it a random distribution for
# which the mean (peak of the curve) is 10, the standard deviation is 5, and the size of
# the returned array is 4 rows by 5 columns. Print bell_curve

bell_curve = np.random.normal(
    loc=10,      # mean (center of the curve)
    scale=5,     # standard deviation
    size=(4, 5)  # 4 rows, 5 columns
)

print(bell_curve)

[[10.16252713 16.15438155  9.67616624 11.10177318  7.66606163]
 [11.92603815 13.3896678   8.0696482  11.16494713  6.17382243]
 [11.46320073  6.10236425  3.73267766  6.46645981  9.60872071]
 [ 9.48695321  9.10813132  9.13793273  4.10662418 13.41802917]]
