# Exercise 1.C Performing operations on Arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
# Create sample arrays (same expressions as r_1 through r_5 from Exercise 1.B)
r_1 = np.random.randint(1, 21, size=2)
r_2 = np.random.randint(1, 21, size=(1, 2))
r_3 = np.random.random(size=(2, 1))
r_4 = np.random.randint(20, 101, size=(4, 5))
r_5 = np.random.random(size=(4, 5))

print("r_1:\n", r_1)
print("r_2:\n", r_2)
print("r_3:\n", r_3)
print("r_4:\n", r_4)
print("r_5:\n", r_5)

r_1:
 [13 18]
r_2:
 [[11  6]]
r_3:
 [[0.45078676]
 [0.58465353]]
r_4:
 [[25 51 31 75 72]
 [68 47 48 81 41]
 [63 37 26 76 51]
 [21 63 25 58 38]]
r_5:
 [[0.29670011 0.09416949 0.38635318 0.81694483 0.2178094 ]
 [0.9396578  0.35110747 0.4791719  0.04920785 0.69199602]
 [0.69048444 0.09097967 0.84245976 0.16340249 0.87178631]
 [0.12839297 0.376809   0.6012822  0.1025531  0.17243705]]


## Permutations

In [3]:
print(r_4)

[[25 51 31 75 72]
 [68 47 48 81 41]
 [63 37 26 76 51]
 [21 63 25 58 38]]


In [4]:
#Use np.random.shuffle to shuffle the values in r_4. Then print r_4 again to view the results
np.random.shuffle(r_4)
print(r_4)

[[21 63 25 58 38]
 [25 51 31 75 72]
 [68 47 48 81 41]
 [63 37 26 76 51]]


When using `np.random.shuffle` on a 2D array, NumPy shuffles the array
along the first axis. This means the rows are rearranged, but the values
within each row stay in the same order.


In [6]:
# Create a new variable named new_shuffle, and assign it the value of a random
# permutation of r_4. Print new_shuffle, and then print r_4 again to compare values
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)

[[63 37 26 76 51]
 [25 51 31 75 72]
 [68 47 48 81 41]
 [21 63 25 58 38]]


In [7]:
print(r_4)

[[21 63 25 58 38]
 [25 51 31 75 72]
 [68 47 48 81 41]
 [63 37 26 76 51]]


You would use `shuffle` when you want to randomly reorder the elements
of an array *in place* and you do not need to keep the original order.

You would use `permutation` when you want a shuffled version of the
array but still want to keep the original array unchanged.

## Mathematical Operations

In [16]:
# Print r_1 and its shape to understand its size and structure
print("r_1:", r_1)
print("Shape of r_1:", r_1.shape)  # .shape tells us how many rows and columns

# Print r_2 and its shape
print("r_2:", r_2)
print("Shape of r_2:", r_2.shape)

# Use np.add() to add the arrays element-by-element
# np.add is used instead of + because it makes broadcasting behavior explicit
result = np.add(r_1, r_2)

# Print the result and its shape
print("Result of r_1 + r_2:", result)
print("Shape of result:", result.shape)


r_1: [13 18]
Shape of r_1: (2,)
r_2: [[11  6]]
Shape of r_2: (1, 2)
Result of r_1 + r_2: [[24 24]]
Shape of result: (1, 2)


In [17]:
# Print starting values and shapes
print ("r_1:", r_1)
print ("Shape of r_1:", r_1.shape)

print("r_3:", r_3)
print("Shape of r_3:", r_3.shape)

# Add r_1 and r_3 using np.add
# NumPy attempts broadcasting to make shapes compatible
result = np.add(r_1, r_3)

print("Result of r_1 + r_2:", result)
print("Shape of result:", result.shape)

r_1: [13 18]
Shape of r_1: (2,)
r_3: [[0.45078676]
 [0.58465353]]
Shape of r_3: (2, 1)
Result of r_1 + r_2: [[13.45078676 18.45078676]
 [13.58465353 18.58465353]]
Shape of result: (2, 2)


In [21]:
# Print arrays and shapes before operation
print("r_2:", r_2)
print("Shape of r_2:", r_2.shape)

print("r_4:", r_4)
print("Shape of r_4:", r_4.shape)

# Add arrays using broadcasting rules
# r_2 will be broadcast across rows of r_4
result = np.add(r_2, r_4)

print("Result of r_2 + r_4:", result)
print("Shape of result:", result.shape)

# r_2 has shape (1,2) and r_4 has shape (4,5)
# Broadcasting fails because the number of columns (2 vs 5) does not match
# NumPy requires dimensions to be equal or one of them to be 1

r_2: [[11  6]]
Shape of r_2: (1, 2)
r_4: [[21 63 25 58 38]
 [25 51 31 75 72]
 [68 47 48 81 41]
 [63 37 26 76 51]]
Shape of r_4: (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [22]:
# Create an expression to illustrate what happens when you add r_1 and r_4
# This operation will raise an error because r_1 and r_4
# have incompatible shapes for broadcasting
np.add(r_1, r_4)

# NumPy cannot stretch these arrays to match each other

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [33]:
# Show what happens if you add np.array([1]) to r_4.
print(np.add(np.array([1]),r_4,))

# np.array([1]) acts like a single number
# It is added to every value in r_4

[[22 64 26 59 39]
 [26 52 32 76 73]
 [69 48 49 82 42]
 [64 38 27 77 52]]


In [39]:
# Show what happens if you add np.array([[1]]) to r_4.
#print(np.add(np.array([[1]]),r_4,))
print(np.add(r_4, np.array([[1]])))


# The shape stays the same
# The array layout stays the same
# Only the values increase by 1
# NumPy expands [[1]] to match the shape of r_4.
# Then 1 is added to every element in r_4

[[22 64 26 59 39]
 [26 52 32 76 73]
 [69 48 49 82 42]
 [64 38 27 77 52]]


In [41]:
# Show what happens if you add np.array([1,1,1,1,1]) to r_4.
print(np.add(np.array([1, 1, 1, 1, 1]), r_4))

# np.array([1, 1, 1, 1, 1]) → shape (1,5)
# r_4 → shape (4,5)
# NumPy is pretending the small array is bigger just for the calculation.
# This array has the same number of columns as r_4
# It gets added row-by-row across r_4
# The array is extended only for the calculation
# r_4 keeps its original shape

[[22 64 26 59 39]
 [26 52 32 76 73]
 [69 48 49 82 42]
 [64 38 27 77 52]]


In [42]:
# What happens if you add np.array([[1],[1]]) to r_4? Add a comment to the
# cell with the error message this produces.
print(np.add(np.array([[1],[1]]), r_4))

# ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 
# This is a column vector with shape (2,1)
# It does NOT match r_4's number of rows (4),
# so broadcasting fails

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Broadcasting allows NumPy to perform operations on arrays with different shapes.

How it works:
- NumPy compares shapes from right to left
- Dimensions must match OR one of them must be 1
- If compatible, the smaller array is stretched to match the larger one

When using np.add:
- Values are added element-by-element
- The final shape is determined by the largest compatible shape

## Rounding

In [46]:
# Print r_3 to display the values you’ll be working with for the next few cells.
print(r_3)

[[0.45078676]
 [0.58465353]]


In [47]:
# Round the values in r_3 using trunc.
print("trunc:\n", np.trunc(r_3))

# trunc removes the decimal part and keeps only the integer part
# It simply cuts off the number (no rounding up or down)

trunc:
 [[0.]
 [0.]]


In [48]:
# Round the values in r_3 using fix.
print("fix:\n", np.fix(r_3))

# fix works like trunc for positive numbers
# It removes the decimal part (towards zero)

fix:
 [[0.]
 [0.]]


In [49]:
# Round the values in r_3 using floor.
print("floor:\n", np.floor(r_3))

# floor always rounds DOWN to the nearest whole number
# Since r_3 values are between 0 and 1, result will always be 0


floor:
 [[0.]
 [0.]]


In [50]:
# Round the values in r_3 using ceil.
print("ceil:\n", np.ceil(r_3))
    
# ceil always rounds UP to the nearest whole number
# Since r_3 values are between 0 and 1, result will always be 1

ceil:
 [[1.]
 [1.]]


In [51]:
# Round the values in r_3 using round, to 2 decimal places.
print("round (2 decimals):\n", np.round(r_3, 2))

# round() rounds numbers to a specific number of decimal places
# Here we keep only 2 decimal places

round (2 decimals):
 [[0.45]
 [0.58]]


## Cumulative Operations 

In [55]:
# Print r_4 to display the values you’ll be working with for the next few cells.
print(r_4)


[[21 63 25 58 38]
 [25 51 31 75 72]
 [68 47 48 81 41]
 [63 37 26 76 51]]


In [59]:
# Print the sum of all values in r_4.
total = np.sum(r_4)
print("Total sum of all elements in r_4:", total)

Total sum of all elements in r_4: 997


In [60]:
# Print the sum of elements along the 0 axis for r_4.
# axis=0 means column-wise sum (top to bottom)
col_sum = np.sum(r_4, axis=0)

print("Sum along axis 0 (columns):", col_sum)

Sum along axis 0 (columns): [177 198 130 290 202]


In [61]:
# Print the sum of elements along the 1 axis for r_4.
# axis=1 means row-wise sum (left to right)
row_sum = np.sum(r_4, axis=1)

print("Sum along axis 1 (rows):", row_sum)

Sum along axis 1 (rows): [205 254 285 253]


In [62]:
# Print the cumulative sum (rolling total) of values in r_4.
# cumsum adds values step-by-step in a single line (flattened array)
cum_total = np.cumsum(r_4)
print("Cumulative sum (flattened):", cum_total)

Cumulative sum (flattened): [ 21  84 109 167 205 230 281 312 387 459 527 574 622 703 744 807 844 870
 946 997]


In [65]:
# Print the cumulative sum (rolling total) of values along the 0 axis for r_4.
# cumulative sum column by column
# cumsum with axis=0 adds values down each column (top to bottom)
cum_axis0 = np.cumsum(r_4, axis=0)
print("Cumulative sum along axis 0:\n", cum_axis0)

Cumulative sum along axis 0:
 [[ 21  63  25  58  38]
 [ 46 114  56 133 110]
 [114 161 104 214 151]
 [177 198 130 290 202]]


## Grocery Problem

In [66]:
# Create two new variables, bag1 and bag2
# Order: [vegetables, fruits, snacks, beverages]

bag1 = np.array([2, 3, 4, 0])  # 2 veg, 3 fruit, 4 snacks, 0 drinks
bag2 = np.array([4, 0, 1, 2])  # 4 veg, 0 fruit, 1 snack, 2 drinks

print("Bag 1:", bag1)
print("Bag 2:", bag2)

Bag 1: [2 3 4 0]
Bag 2: [4 0 1 2]


In [67]:
# Sum each bag separately
bag1_total = np.sum(bag1)
bag2_total = np.sum(bag2)

print(f"The first bag contains {bag1_total} items, and the second bag contains {bag2_total} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [70]:
# Add bag1 and bag2 element-wise
totals = bag1 + bag2

print(
    f"There are {totals[0]} vegetables, {totals[1]} fruits, {totals[2]} boxes of snacks, and {totals[3]} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [71]:
# Ali has full 5 days of data (Mon–Fri)
ali = np.array([5, 4, 6, 4, 2])

# Ben missed Monday, so we use 0 or we just start from Tuesday
ben = np.array([0, 5, 5, 3, 4])

# Carla missed Wednesday, so we put 0 for that day
carla = np.array([3, 6, 0, 3, 4])

print("Ali:", ali)
print("Ben:", ben)
print("Carla:", carla)

Ali: [5 4 6 4 2]
Ben: [0 5 5 3 4]
Carla: [3 6 0 3 4]


In [72]:
# Stack all people into one 2D array (rows = people, columns = days)
all_knocks = np.array([ali, ben, carla])

print("All knocks:\n", all_knocks)

All knocks:
 [[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [73]:
# Sum across days (axis=1 → row-wise)
# This gives total for each person
person_totals = np.sum(all_knocks, axis=1)

# Total for the whole group
group_total = np.sum(all_knocks)

print("Total per person:", person_totals)
print("Group total:", group_total)

Total per person: [21 17 16]
Group total: 54


In [74]:
# Sum across people (axis=0 → column-wise per day)
daily_total = np.sum(all_knocks, axis=0)

print("Daily total knocks:", daily_total)

# Cumulative (rolling) total across the week
rolling_knocks = np.cumsum(daily_total)

print("Rolling total knocks:", rolling_knocks)

Daily total knocks: [ 8 15 11 10 10]
Rolling total knocks: [ 8 23 34 44 54]


In [75]:
# Every 2 knocks = 1 vote → multiply by 0.5
estimated_votes = rolling_knocks * 0.5

print("Estimated rolling votes:", estimated_votes)

Estimated rolling votes: [ 4.  11.5 17.  22.  27. ]


In [ ]:
# We sum knocks by day, then compute a running total, then estimate votes (1 vote per 2 knocks)