# Continuing with NumPy PG 92

In [16]:
import numpy as np 

In [17]:
start_list = [(1,2,3), ('a', 'b', 'c')]
example_a = np.array(start_list)
print (example_a.dtype)

<U21


In [18]:
num_abc = np.array(start_list, dtype="U")


In [19]:
print(num_abc)

[['1' '2' '3']
 ['a' 'b' 'c']]


In [20]:
#use int datatype, converting from float

nums = [1.0, 1.1, 2.0, 2.1]

nums_arr = np.array(nums, dtype = 'i')  # array can ONLY CONTAINE ONE TYPE OF VALUE 
print(nums_arr)
print(nums_arr.dtype)

[1 1 2 2]
int32


In [21]:
# ARRAY IN LOOPS

In [22]:
arr3d= np.array([
    [[8,7], [6,5]],
    [[4,3], [2,1]],
    [[10,11], [12,13]]
])

In [23]:
for i in arr3d:
    print(i)

[[8 7]
 [6 5]]
[[4 3]
 [2 1]]
[[10 11]
 [12 13]]


In [24]:
for blueberry in arr3d:
    for raspberry in blueberry:
        print(raspberry)

[8 7]
[6 5]
[4 3]
[2 1]
[10 11]
[12 13]


In [26]:
for i in arr3d:
    for x in i:
        for gooseberry in x:
            print(gooseberry)

8
7
6
5
4
3
2
1
10
11
12
13


In [27]:
for i in arr3d:
    for x in i:
        print(sum(x))

15
11
7
3
21
25


## Concatenating and Stacking Arrays

In [31]:
# array concatenation

arr_a= np.array([1,2,3])
arr_b = np.array([4,5,6])

arr_c = np.concatenate((arr_a, arr_b)) # concatenation results in the same number of dimensions as the starting arrays
print(arr_c)

[1 2 3 4 5 6]


In [33]:
arr_d = np.stack((arr_a, arr_b)) # stack adds a new dimension to the resulting array
print(arr_d)

[[1 2 3]
 [4 5 6]]


In [36]:
print(arr_d.ndim)
print(arr_d.shape)

2
(2, 3)


In [38]:
combo_d = np.concatenate((arr_d, arr_d))
print(combo_d)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [39]:
print(combo_d.ndim)
print(combo_d.shape)

2
(4, 3)


In [40]:
combo_d2 = np.concatenate((arr_d, arr_d), axis = 1)
print(combo_d2)


[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [43]:
# using a practical example

# say I've got 2 sets of exam grades, from a original exam date and a later makeup for some students who needed it

exam_scores = [.78, .89, .92, .82, .99]
exam_scores_makeup = [.90, .85]


exam_all = np.concatenate((np.array(exam_scores), np.array(exam_scores_makeup)))
exam_all = np.concatenate((exam_scores, exam_scores_makeup))
print(exam_all)

[0.78 0.89 0.92 0.82 0.99 0.9  0.85]


In [47]:
project_scores = np.array([.88, .91, .97, .85, .96, .89, .87])

gradebook = np.stack((exam_all, project_scores))
print(gradebook)

[[0.78 0.89 0.92 0.82 0.99 0.9  0.85]
 [0.88 0.91 0.97 0.85 0.96 0.89 0.87]]


In [48]:
### Working with hstack, vstack, dstack

In [49]:
first_trio = np.array([1, 2, 3])
second_trio = np.array([4, 5, 6])

print(first_trio.ndim)
print(first_trio.shape)

1
(3,)


In [50]:
six_with_hstack = np.hstack((first_trio, second_trio)) # stacks each 1D array "horizontally" end-to-end
print(six_with_hstack)

[1 2 3 4 5 6]


In [52]:
six_with_hstack = np.vstack((first_trio, second_trio)) #stacks each 1D array on top of each other "vertically"
print(six_with_hstack)

[[1 2 3]
 [4 5 6]]


In [70]:
six_with_dstack = np.dstack((first_trio, second_trio)) #stacks each 1D array on top of each other "vertically"
print(six_with_dstack)

[[[1 4]
  [2 5]
  [3 6]]]


In [71]:
print(six_with_dstack.ndim)

3


In [72]:
print(six_with_dstack.shape)


(1, 3, 2)


In [73]:
first_quartet = np.array ([1, 2, 3, 10])
second_quartet = np.array([4, 5, 6, 20])

print("using hstack:")
print(np.hstack((first_quartet, second_quartet)))
print(f'\nursing vstack:')
print(np.vstack((first_quartet, second_quartet)))
print(f'\nursing dstack: ')
print(np.dstack((first_quartet, second_quartet)))



using hstack:
[ 1  2  3 10  4  5  6 20]

ursing vstack:
[[ 1  2  3 10]
 [ 4  5  6 20]]

ursing dstack: 
[[[ 1  4]
  [ 2  5]
  [ 3  6]
  [10 20]]]


In [77]:
a = six_with_vstack
b = six_with_vstack
c = six_with_vstack

print(np.hstack((a, b, c))) # hstack will give you a resulting array with the same # of dimensions

NameError: name 'six_with_vstack' is not defined

In [78]:
print(np.dtack((a,b)))


AttributeError: module 'numpy' has no attribute 'dtack'

In [76]:
# what do we get if we use vstack with 3D arrays?

print(np.dstack((np.dstack((a,b)), np.dstack((a,b)))))

NameError: name 'a' is not defined

In [79]:
print([x * 2 for x in range(4)]) 



[0, 2, 4, 6]


In [80]:
int('15') + 5 

20

In [81]:
print(bool(0))


False
