## Continuing with NumPy 

### Briefly, review hstack/ vstack / dstack

In [9]:
import numpy as np

In [28]:
a = [0, 1, 2, 3, 11, 12]
b = [4, 5, 6, 7, 13, 14]

print(np.hstack((a,b))) # equivalent to concatenating on the 0 axis 
print(np.vstack((a,b))) # concatenating on the 1 axis
print(np.dstack((a,b)))  # concatenating on the 2 axis ,it always return in 3 dimension     

[ 0  1  2  3 11 12  4  5  6  7 13 14]
[[ 0  1  2  3 11 12]
 [ 4  5  6  7 13 14]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]
  [11 13]
  [12 14]]]


In [29]:
print(np.concatenate((a,b)))

print(np.stack((a,b)))

print(np.stack((a,b), axis = 1)) # not equivalent to dstack , as dstack will return 3D array

# stacking is adding another dimension 
# concatenate is on the same dimension 

[ 0  1  2  3 11 12  4  5  6  7 13 14]
[[ 0  1  2  3 11 12]
 [ 4  5  6  7 13 14]]
[[ 0  4]
 [ 1  5]
 [ 2  6]
 [ 3  7]
 [11 13]
 [12 14]]


In [30]:
# so splitting arrays i breaking arrays apart 
print(np.array_split(a, 2))

[array([0, 1, 2]), array([ 3, 11, 12])]


In [31]:
print(np.array_split(a, 3))

[array([0, 1]), array([2, 3]), array([11, 12])]


In [32]:
print(np.array_split(a, 4)) # allows for an uneven split

[array([0, 1]), array([2, 3]), array([11]), array([12])]


In [39]:
ab = np.stack((a,b))

print(ab)

print(np.hsplit(ab, 2)) # hsplir works on the axis, is not forgiving of uneven splits

[[ 0  1  2  3 11 12]
 [ 4  5  6  7 13 14]]
[array([[0, 1, 2],
       [4, 5, 6]]), array([[ 3, 11, 12],
       [ 7, 13, 14]])]


In [40]:
ab = np.stack((a,b))

print(ab)

print(np.vsplit(ab, 2))

[[ 0  1  2  3 11 12]
 [ 4  5  6  7 13 14]]
[array([[ 0,  1,  2,  3, 11, 12]]), array([[ 4,  5,  6,  7, 13, 14]])]


In [41]:
print(np.hsplit(ab, 2))

[array([[0, 1, 2],
       [4, 5, 6]]), array([[ 3, 11, 12],
       [ 7, 13, 14]])]


In [43]:
# let's put this into context with some sales data
full_year = np.array([[100, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220],
                     [200, 210, 190, 205, 220, 230, 240, 235, 225, 215, 205, 195],
                     [90, 95, 100, 110, 115, 120, 125, 130, 120, 115, 110, 105]])
# each array is a column
# the "rows" match on th evertical alignment 

In [48]:
quarters = np.array_split(full_year, 4, axis = 1)
print(quarters)
q1, q2, q3, q4 = quarters
print(q1)

[array([[100, 120, 130],
       [200, 210, 190],
       [ 90,  95, 100]]), array([[140, 150, 160],
       [205, 220, 230],
       [110, 115, 120]]), array([[170, 180, 190],
       [240, 235, 225],
       [125, 130, 120]]), array([[200, 210, 220],
       [215, 205, 195],
       [115, 110, 105]])]
[[100 120 130]
 [200 210 190]
 [ 90  95 100]]


In [51]:
by_product = np.array_split(full_year, 3, axis = 0)

prod_a, prod_b, prod_c = by_product

print(prod_a)

[[100 120 130 140 150 160 170 180 190 200 210 220]]


## Using where() to apply a condition to an array

In [ ]:
### where() let you look for a condition 

In [52]:
print(np.where(full_year > 200)) # with only a condition, return an array of matches 

(array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([10, 11,  1,  3,  4,  5,  6,  7,  8,  9, 10]))


In [56]:
print(np.where(full_year > 200, full_year, 'low')) # lets you set a return and not-found value 

[['low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'high'
  'high']
 ['low' 'high' 'low' 'high' 'high' 'high' 'high' 'high' 'high' 'high'
  'high' 'low']
 ['low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low' 'low']]


In [57]:
print(full_year[full_year > 200]) # drop the not matching values 
# filtering with bracket notation return only matches 

[210 220 210 205 220 230 240 235 225 215 205]


In [58]:
print(full_year[full_year % 3 == 0]) # % is the reminding 
# will return values divisible by 3 

[120 150 180 210 210 240 225 195  90 120 120 105]


In [60]:
div_by_3 = (full_year % 3 == 0)

print(full_year[div_by_3]) # this is the pattern on pg 15 in the student guide 

[120 150 180 210 210 240 225 195  90 120 120 105]


## Sorting array values

In [62]:
num_x = np.array([(7,6,2,1,9),(5,3,9,1,0)])

In [64]:
print(np.sort(num_x))  #sort will return a copy of the array with sorting applied

[[1 2 6 7 9]
 [0 1 3 5 9]]


In [68]:
num_sorted = np.sort(num_x)

In [69]:
print(num_x)
print(num_sorted)

[[7 6 2 1 9]
 [5 3 9 1 0]]
[[1 2 6 7 9]
 [0 1 3 5 9]]


In [70]:
str_x = ('I-1456', 'InstaDerp', '110-XR', '#Zenith', 12, '14', '110', 145)
str_x = np.array (str_x)
print(str_x)


['I-1456' 'InstaDerp' '110-XR' '#Zenith' '12' '14' '110' '145']


In [71]:
print (np.sort(str_x))

['#Zenith' '110' '110-XR' '12' '14' '145' 'I-1456' 'InstaDerp']


## Random in NumPy

In [72]:
# when calling the random module in NumPy:
# np.random. [function name]

In [74]:
some_ints = np.random.randint(100, size = (5)) # assumes a zero start == from 0 to 100
print(some_ints)

[70 27 64 68 52]


In [76]:
more_ints = np.random.randint(50, 100, size = (5,3)) # assumes a zero  == from 0 to 100
print(more_ints)

[[69 97 87]
 [61 88 95]
 [68 82 76]
 [63 97 86]
 [81 66 78]]


In [78]:
print(np.random.rand(5, 3))

[[0.60429124 0.98097717 0.33278395]
 [0.00289259 0.78814999 0.91580064]
 [0.32273573 0.8400368  0.72246615]
 [0.26145379 0.87836641 0.73961083]
 [0.5733225  0.07305212 0.17029701]]


In [91]:
# working with choice()
print(some_ints) # starting values to choose from 
print(np.random.choice(some_ints))

[70 27 64 68 52]
68


In [92]:
sales_sample = np.random.choice(str_x, size = (4,10))
print(sales_sample)

[['110-XR' '12' '145' '145' '145' '110' '#Zenith' 'I-1456' '14'
  'InstaDerp']
 ['14' '110' '110' '110-XR' '110-XR' 'InstaDerp' '110' '110' 'I-1456'
  '110']
 ['14' '12' '#Zenith' '110-XR' '145' 'InstaDerp' '110' '110-XR' '110'
  'InstaDerp']
 ['InstaDerp' '110' 'InstaDerp' '145' '110' 'InstaDerp' '#Zenith' '14'
  '145' '12']]


In [94]:
# choice() can also be used to assign probability values

weigthed_sales_sample = np.random.choice(str_x, size = (4, 10), p = [.1, .2, .2, .2, .1, .05, .05, .05, .05])
print(weighted_sales_sample)

ValueError: 'a' and 'p' must have same size

In [86]:
print(str_x)

['I-1456' 'InstaDerp' '110-XR' '#Zenith' '12' '14' '110' '145']


In [95]:
# for starting values:


## Creating a distribution curve using normal()

In [99]:
x = np.random.normal(loc=5, scale = 2, size =(30))
print(x)

[ 4.65213307  8.15241981  7.10883282 -0.03902453  5.75592328  9.14195839
  2.30288021  4.42801373  5.44869798  8.24234692  2.6617938   1.99473143
  4.15633109  4.22352666  7.32130022  1.94754508 -0.1139741   7.56079515
  7.87934629  6.39179398  7.81272469  5.7341569   7.14686681  2.68929617
  2.77345186  6.12557439  7.56681469  5.83194337  8.11893572  0.22705346]


## Shuffle / Permutation


In [100]:
print(str_x)

['I-1456' 'InstaDerp' '110-XR' '#Zenith' '12' '14' '110' '145']


In [101]:
# permutation will return a new array / a copy with the results in a new order 
print(np.random.permutation(str_x))


['14' '12' '110-XR' '#Zenith' 'InstaDerp' '110' '145' 'I-1456']


In [102]:
print(str_x)

['I-1456' 'InstaDerp' '110-XR' '#Zenith' '12' '14' '110' '145']


In [103]:
# shuffle is an in-place operation that changes the order od the starting array 
print(np.random.shuffle(str_x))
print(str_x)

None
['145' '12' '#Zenith' '110-XR' '14' 'I-1456' '110' 'InstaDerp']


## Ufuncs in NumPy

In [106]:
sale_price = np.array([2.99, 12.99, 3.50, 4.50, 17.90, 22.00])

discount_amount = np.array([0, 0, 3.50, .50, 3, 0])

print(sale_price + discount_amount)

[ 2.99 12.99  7.    5.   20.9  22.  ]


In [107]:
print(np.add(sale_price, discount_amount))

[ 2.99 12.99  7.    5.   20.9  22.  ]


In [109]:
print(np.multiply(sale_price, .8))

[ 2.392 10.392  2.8    3.6   14.32  17.6  ]


In [111]:
print(np.round(np.multiply(sale_price, .8), 2))

[ 2.39 10.39  2.8   3.6  14.32 17.6 ]


In [113]:
# round() applies "banker's roundind"
# rounding at 5 rounds towars the nearest even value 

apple = np.array((.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5))

print(np.round(apple))


[0. 2. 2. 4. 4. 6. 6.]


In [114]:
babble = [.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5]
print(round(sum(babble)))

24
